phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pm2
      - npm install          # install dependencies at repo root if needed

  build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  base-directory: .  # repo root
