version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pm2

  build:
    commands:
      - echo "Building backend..."
      - cd backend && npm install && cd ..
      - echo "Building frontend (if needed)..."
      - cd frontend && npm install && cd ..
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  base-directory: .