version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pm2

  build:
    commands:
      - npm install
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  base-directory: .   # repo root, not backend
