name: "Frontend CI/CD Pipeline"

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main 
  workflow_dispatch:         
        
jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with: 
          node-version: 20
            
      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Install Dependencies
        run: | 
          npm ci
          npm install pm2 -g
        working-directory: frontend/         

  deploy: 
    needs: build
    runs-on: ubuntu-latest   
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        
      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Transfer Files and Deploy
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@54.162.134.75 "mkdir -p ~/project/frontend"
      
          scp -i ~/.ssh/id_rsa -r frontend/* ec2-user@54.162.134.75:~/project/frontend
      
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@54.162.134.75 "
            # Install Node.js if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
              sudo yum install -y nodejs
            fi
            
            cd ~/project/frontend &&
            npm install &&
            npm run  build 
          "